#pragma once

enum NodeType {
    NODE_IMAGE_INPUT,
    NODE_OUTPUT,
    NODE_BRIGHTNESS_CONTRAST,
    NODE_BLUR,
    NODE_THRESHOLD,
    NODE_EDGE_DETECTION,
    NODE_BLEND,
    NODE_NOISE,
    NODE_CONVOLUTION,
    NODE_COLOR_SPLIT
};
